include(ExternalProject)

set(openal_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/openal)

set(openal_CMAKE_ARGS
	-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
	-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
	-DALSOFT_CONFIG=OFF
	-DALSOFT_EXAMPLES=OFF
	-DALSOFT_NO_CONFIG_UTIL=ON
	-DALSOFT_UTILS=OFF
	-DLIBTYPE=STATIC
)

ExternalProject_Add(openal_build
	PREFIX ${openal_PREFIX}

	DOWNLOAD_DIR ${ER_CONTRIB_DOWNLOAD_DIR}

	GIT_REPOSITORY git://repo.or.cz/openal-soft.git

	INSTALL_DIR ${ER_TARGET_CONTRIB_OUT_DIR}
	CMAKE_ARGS ${openal_CMAKE_ARGS}
)

add_library(openal STATIC IMPORTED)
set_target_properties(openal PROPERTIES
	IMPORTED_LOCATION ${ER_TARGET_CONTRIB_OUT_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}openal${CMAKE_STATIC_LIBRARY_SUFFIX}
)
add_dependencies(openal openal_build)
