include(ExternalProject)

set(glfw_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/glfw)

set(glfw_CMAKE_ARGS
	-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
	-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
	-DGLFW_BUILD_EXAMPLES=OFF
	-DGLFW_BUILD_TESTS=OFF
	-DGLFW_BUILD_DOCS=OFF
	-Wno-dev
)

ExternalProject_Add(glfw_build
	PREFIX ${glfw_PREFIX}

	DOWNLOAD_DIR ${ER_CONTRIB_DOWNLOAD_DIR}

	GIT_REPOSITORY git://github.com/glfw/glfw.git

	INSTALL_DIR ${ER_TARGET_CONTRIB_OUT_DIR}
	CMAKE_ARGS ${glfw_CMAKE_ARGS}
)

add_library(glfw STATIC IMPORTED)
set_target_properties(glfw PROPERTIES
	IMPORTED_LOCATION ${ER_TARGET_CONTRIB_OUT_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}glfw3${CMAKE_STATIC_LIBRARY_SUFFIX}
)
add_dependencies(glfw glfw_build)
