include(ExternalProject)

set(glew_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/glew)

set(glew_CMAKE_ARGS
	-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
	-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
	-Wno-dev
)

ExternalProject_Add(glew_build
	PREFIX ${glew_PREFIX}

	DOWNLOAD_DIR ${ER_CONTRIB_DOWNLOAD_DIR}

	URL http://sourceforge.net/projects/glew/files/glew/1.10.0/glew-1.10.0.zip/download
	URL_MD5 594eb47b4b1210e25438d51825404d5a

	PATCH_COMMAND ${CMAKE_COMMAND} -E copy_if_different ${ER_SCRIPTS_DIR}/cmake/modules/glew.cmake <SOURCE_DIR>/CMakeLists.txt

	INSTALL_DIR ${ER_TARGET_CONTRIB_OUT_DIR}
	CMAKE_ARGS ${glew_CMAKE_ARGS}
)

add_library(glew STATIC IMPORTED)
set_target_properties(glew PROPERTIES
	IMPORTED_LOCATION ${ER_TARGET_CONTRIB_OUT_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}glew${CMAKE_STATIC_LIBRARY_SUFFIX}
)
add_dependencies(glew glew_build)
